### ISSUE TITLE
Header video has fixed size, gets blown out of proportion

### ISSUE THREAD

**Issue by gdaleks** [godaddy/wp-escapade-theme#107]
Initial WordPress.org issue: https://wordpress.org/support/topic/header-image-issue-11/

Replicated on my test site: https://prnt.sc/un2uhi

The custom video header has a fixed width and height, which causes this issue.

I added the following code to the Additional CSS area which fixed it:
`#wp-custom-header-video{
	width:100%;
	height:auto;
}`

Result: https://prnt.sc/un2vfd

**Comment by jadedartist** [comment]
Didn't work for me in Escapade WordPress theme.  :/

**Comment by PavleMarjanovic** [comment]
@gdaleks 
Can we re-open this one and take another look?

**Comment by jadedartist** [comment]
Hi Pavle,

Any word on the fix?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
