### ISSUE TITLE
OceanWP mobile menu won't stay open

### ISSUE THREAD

**Issue by baconbutty20** [godaddy/wp-escapade-theme#108]
Recently I have noticed that the main menu, side bar activated rather than top bar, works fine and submenus open and close as would be expected on a desktop, however,  when opening the site in mobile mode, the main dropdown menu opens but when activating the + sign to open the submenu's,  they open and close immediately and therefore the sub menus are not usable.
Has any one else had this problem and where they able to resolve it please. 
Theme Name: 		   OceanWP
 * Text Domain: 	   oceanwp
 * Version:            1.9.0
 * Tested up to:       5.5
 * Requires at least:  5.3
WP version 5.5.3
website https://656squadron.org

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
