### ISSUE TITLE
After updating from WP 5.5.3 to 5.7.1, video header breaks apart

### ISSUE THREAD

**Issue by gdandrija** [godaddy/wp-escapade-theme#112]
Issue confirmed to be related to the theme and replicated on the local environment

Screenshot showing issue: https://i.imgur.com/Xhh3iie.jpg
How it should look like: https://i.imgur.com/sFXJSyW.jpg

The reason why this happens is the fact the video-header CSS class does not seem to be added any longer.

The issue can be temporarily solved by adding the CSS code without the missing class, but this will affect non-video pages as well:

`.site-header {
  overflow: hidden;
  height: 100%;
  padding: 0;
  background-color: #000;
  color: #000; }
  .site-header #wp-custom-header {
    position: absolute;
    height: 100vh;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    margin: auto; }
    .site-header.video-header #wp-custom-header img {
      display: none; }
  .site-header #wp-custom-header-video-button {
    position: absolute;
    left: 1em;
    top: 25vh;
    opacity: 0.5;
    z-index: 1; }
  .site-header iframe#wp-custom-header-video {
    height: 100%; }`

The issue is present with all other plugins disabled

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
