### ISSUE TITLE
Editor scrolling broken in latest wordpress update

### ISSUE THREAD

**Issue by nergmada** [godaddy/wp-escapade-theme#30]
Having recently spun up a new GoDaddy wordpress, I have found that this theme has an issue where the Post/Page Editor TinyMCE seems to have problems scrolling correctly. The behaviour prevents editing or writing of new posts.

The behaviour seems to be broken it two distinct things. Firstly, the editor continues to grow slowly downwards adding new lines every so often without any action having taken place in the editor itself.

Furthermore, when typing in the editor adding a new line (i.e. hitting enter) results in odd scrolling up behaviour which scrolls more and more with every new line.

I believe this is a theme specific issue it seems as switching themes seems to stop this happening. Hit me up if any additional help is required fixing this

**Comment by jonathanbardo** [comment]
@nergmada Thanks for reporting this. It seems like the CSS we add for the editor is causing the issue. We will try to patch this as soon as possible.
