### ISSUE TITLE
Site Title Text Customize Option has No effect

### ISSUE THREAD

**Issue by donavynelliott** [godaddy/wp-escapade-theme#43]
Under Appearance -> Customize -> Colors -> Header

The option for Site Title Text color has no effect on the site title text.

**Comment by EvanHerman** [comment]
Hi @donavynelliott,

You are correct. I just did some testing and I am able to replicate the issue on my end as well.

We are currently working towards a new release for escapade that has a few enhancements. I will include this bug to get wrapped into the 1.1.0 release, and I'll get working on a fix for it today.
