### ISSUE TITLE
primer_video_header function not found

### ISSUE THREAD

**Issue by donavynelliott** [godaddy/wp-escapade-theme#48]
After uploading a custom header image, this error is received.

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'primer_video_header' not found or invalid function name in /home/installation_directory/public_html/domain.com/wp-includes/class-wp-hook.php on line 298

**Comment by EvanHerman** [comment]
Hi @donavynelliott,

What version of Primer & Escapade do you currently have installed? I don't believe that `primer_video_header` has yet been introduced into a public stable release of Escapade, which may be why you are seeing the error.

You may want to try installing Escapade v1.0.0, until we have had a chance to release the new versions of Primer and Escapade.

https://github.com/godaddy/wp-escapade-theme/releases/tag/v1.0.0

**Comment by donavynelliott** [comment]
Yes, you are correct this was the development version. I got the two installations mixed up.
