### ISSUE TITLE
Change Base Color Scheme resets 'Display Site Title and Tagline' Setting

### ISSUE THREAD

**Issue by donavynelliott** [godaddy/wp-escapade-theme#49]
If you change the base color scheme under appearance->customize->colors if will reset the display site title and tagline Boolean under appearance->customize->site identity to true.

**Comment by EvanHerman** [comment]
Hi @donavynelliott 

Thanks for reporting this here. I was able to replicate the issue on my end. I will work on a patch and see if we can get this fix in the next release for you.

Evan

**Comment by EvanHerman** [comment]
I've migrated this issue over to the main Primer github repo, since it also occurs in the base theme.
