### ISSUE TITLE
Change hero text color. Escapade theme.

### ISSUE THREAD

**Issue by JoshuaWuebben** [godaddy/wp-escapade-theme#54]
How do I change the text color of the hero header image in the escapade theme.

**Comment by EvanHerman** [comment]
Hi @JoshuaWuebben,

You can customize the text color in the hero header using the customizer. From the admin dashboard if you click on 'Appearance > Customize' this will bring you into the customizer.

From there you can click on 'Colors > Header', which will display the customization options for the header. One of those options is the text color for the hero.

Example:
![Example](https://cldup.com/F2zdyHSbd5.png)
