### ISSUE TITLE
WooCommerce: remove the "cart preview" section in the main menu.

### ISSUE THREAD

**Issue by nathanp123** [godaddy/wp-escapade-theme#55]
I've tried anything I can think of; is there any way to remove the "Cart Preview" ($0.00, 0 items) area from the menu?
![screen shot 2017-08-13 at 4 14 45 pm](https://user-images.githubusercontent.com/30989341/29254087-9427a05c-8042-11e7-8e22-b1e249ce9776.jpg)

Thanks!

**Comment by EvanHerman** [comment]
Hi @nathanp123 ,

You can disable the "Cart Preview" from the menu by using the `primer_wc_show_cart_menu` filter included in the Primer parent theme.

If you [setup an MU plugin](https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html#how-to-create-a-must-use-plugin) and add the following code to it, the "Cart Preview" section should be disabled.

```php
/**
 * Disable the "Cart Preview" menu item.
 */
add_filter( 'primer_wc_show_cart_menu', '__return_false' );
```

Reference: https://github.com/godaddy/wp-primer-theme/blob/develop/inc/compat/woocommerce.php#L525-L538
