### ISSUE TITLE
continue reading button

### ISSUE THREAD

**Issue by kelwin17** [godaddy/wp-escapade-theme#62]
I added plugin quiz and survey for my website, when i added that quiz to my page i am getting continue reading button.. this is irritating

https://studentcafe.co/quiz

**Comment by EvanHerman** [comment]
From a quick glance, it does look like the quiz plugin is creating a custom post type and then displaying the quiz on post type archive pages:

![Image](https://cldup.com/Pih1d5coqH.png)

**Comment by kelwin17** [comment]
i am using {Quiz And Survey Master} plugin, i saw video where they just paste the quiz shortcut in page and i did same but i am getting continue reading...
