### ISSUE TITLE
Page Titles are not working

### ISSUE THREAD

**Issue by AWcoder** [godaddy/wp-escapade-theme#65]
The titles for my pages are showing up over the header image (white text), over the side menu (white text-barely visible), and below the side menu (black text). I only want one title over the header picture.

How do I remove all the other page titles?
http://handsforhope.us/centro-evangelico/

I also am having a similar issue with my Hero Widget. It is being displayed over the header image on the home page as well as above my menu. I don't want it in both places but I can't find any way to remove the one above the menu.
http://handsforhope.us/

This started happening after I updated to the latest version of the Escapade Theme.

**Comment by AWcoder** [comment]
I fixed the problem. Just needed an update to the Primer theme.

**Comment by EvanHerman** [comment]
Great! I’m glad my email helped get this resolved for you. Sorry I didn’t also respond here, I wasn’t around my computer much this weekend.

If you have any other questions please don’t hesitate to open up a new thread. Have a great week!
