### ISSUE TITLE
How to Hide Page Title without using code

### ISSUE THREAD

**Issue by dagmunn1** [godaddy/wp-escapade-theme#67]
I am using Escapade theme hosted by GoDaddy. I am holding off publishing to my domain until I can find a way to hide the page titles. They show up in the Hero area and are redundant to the side-bar menu (not to mention ruining my Hero image). I have tried a number of "Hide Title" plug-ins but they do not work. How can I (a non-coder) fix this? Thank you.
![hero1](https://user-images.githubusercontent.com/46353608/50651470-add12800-0f40-11e9-9b64-4455da19ca3a.jpg)

**Comment by EvanHerman** [comment]
Hi @dagmunn1 

You should be able to hide those page titles using some minor CSS. You can add the following to your themes 'Additional CSS' section of the customizer. You can get there from the dashboard by navigating to 'Appearance > Customizer > Additional CSS' and adding the below there.

```css
#masthead .page-title {
   display: none;
}```

Let us know how that goes!

Evan

**Comment by dagmunn1** [comment]
Thank you! It worked perfectly!
I wish I would have posted the question here 4 weeks ago, instead of wasting time hunting elsewhere and trying failed plug-ins!
I appreciate the simple and concise instructions.
Thank you! Dagmunn1
