### ISSUE TITLE
How to hide cart total from main menu

### ISSUE THREAD

**Issue by dagmunn1** [godaddy/wp-escapade-theme#68]
I am using Escapade theme hosted by GoDaddy. You helped me solve an issue a few days ago - - and I hope you can do it again! 

Our site only offers memberships and takes donations so a WooCommerce cart total in our main menu showing "$0.00" is not needed. I've searched for solutions to hide it and nothing works. These include: .header_cart { display: none; } AND /*Hide shop icon*/a.woo-menu-cart { display: none !important; }	
-- all via the Appearance/Customization section.  Your help again please. Thank you.
![screen shot](https://user-images.githubusercontent.com/46353608/50741767-0ada1180-11bf-11e9-8584-84be6db63275.jpg)

**Comment by EvanHerman** [comment]
Hi @dagmunn1 

If you can post a link to your site, I'd be happy to take a look. You should be able to quickly hide it using some basic CSS.

Evan

**Comment by dagmunn1** [comment]
Hello Evan,

My site is: worldacro.com

Thank you for offering to help!

Dagmar

**Comment by draint3** [comment]
@dagmunn1 how did you get the shopping cart removed?

**Comment by baconbutty20** [comment]
I could do with being able to remove the shopping cart info from the sidebar also please.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
