### ISSUE TITLE
Gutenberg blocks

### ISSUE THREAD

**Issue by RS1981NL** [godaddy/wp-escapade-theme#74]
Hi guys,

this is probably a very stupid question, but after installing the Escapade theme, it seems like it's running the old editor. I miss the blocks to design pages with. What can I do to arrange that?

Thanks!

**Comment by EvanHerman** [comment]
Hi @RS1981NL 

This isn't a limitation of the theme, the block editor should still work when Escapade is installed. If you are using WordPress 5.0 or have the Gutenberg plugin installed the block editor should be enabled.
