### ISSUE TITLE
Wrong text color in post page

### ISSUE THREAD

**Issue by smartmeeter** [godaddy/wp-escapade-theme#76]
About an text color issue in Escapade WordPress theme. How to change to lighter text color in "post page" without changing other text on page? The other text in the theme is displayed correct when you change color in other pages. See the picture example.

![escapade-theme-color-in-post-page](https://user-images.githubusercontent.com/51018502/58367408-3bf17f00-7edf-11e9-947f-ff88bddfee86.jpg)

**Comment by EvanHerman** [comment]
Hi @smartmeeter 

If you use the customizer to alter the colors it will also affect the other pages. You can write some custom code to target specific pages, or alter colors as needed where you want. You can add the custom CSS to the 'Additional CSS' section of the customizer.
