### ISSUE TITLE
Featured image in blog post is too large

### ISSUE THREAD

**Issue by Splinter1234** [godaddy/wp-escapade-theme#78]
No matter what size image I use for the featured image in a blog post, it expands to the width of the page when published.
All I want to see is a thumbnail preview in the list of blog posts.

**Comment by EvanHerman** [comment]
Hi @Splinter1234 

You'll need to write some custom code to alter the size of the thumbnails being displayed on those pages. I'd recommend posting over in the 'Developing with WordPress' forum on WordPress.org:
https://wordpress.org/support/forum/wp-advanced/

Evan
