### ISSUE TITLE
First item in mobile menu not aligned

### ISSUE THREAD

**Issue by Stewdi** [godaddy/wp-escapade-theme#95]
Hi,

I´ve experienced an issue with the first menu item on small screens. It doesnt align with the other menu items.

Any ideas on how this could be solved?

![Screenshot_20200212_1](https://user-images.githubusercontent.com/60975276/74346450-ea13c080-4daf-11ea-8ce9-003576be83cb.jpg)

knd rgrds

**Comment by castle1016** [comment]
I have a similar problem with the first two items in mobile menu.

<img width="495" alt="Schermata 2020-04-14 alle 18 24 57" src="https://user-images.githubusercontent.com/63661472/79249324-5f1d7800-7e7d-11ea-9a3b-c4fb33616fd1.png">

**Comment by rafaelnockmann** [comment]
Escapade is one of the best WordPress themes with vertical navigation for my use case. Sadly that the developer apparently no longer maintains the theme regularly. However, I was able to fix the error with the first item in mobile view by adding some custom CSS in the customizer:
```
div.main-navigation-container nav.main-navigation.open::before {
  clear: both;
}
```
Alternatively, the following snippet can be used:
```
div.main-navigation-container nav.main-navigation.open::before {
  white-space: pre;
}
```

I hope the developer will officially fix the bug.

**Comment by keh2021** [comment]
@Nocksoft Thanks! The first fix worked for me. Last glitch that I had with Escapade is now also gone.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
